// Generated by CoffeeScript 1.12.7
(function() {
  var app, buildDir, config, entry, express, fs, http, io, path, player, port;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  fs = require('fs');

  path = require('path');

  config = null;

  if (fs.existsSync('mulberry.config.json')) {
    config = JSON.parse(fs.readFileSync('mulberry.config.json', 'utf8'));
  }

  buildDir = (config != null) && (config.buildDir != null) ? config.buildDir : 'build';

  app.use(express["static"](buildDir));

  entry = (config != null) && (config.entry != null) ? config.entry : 'index.html';

  app.get('/', function(req, res) {
    return res.sendFile(path.join(process.cwd(), buildDir, entry));
  });

  player = (config != null) && config.player ? config.player : 'player.html';

  app.get(/[A-Z]{4}/, function(req, res) {
    return res.sendFile(path.join(process.cwd(), buildDir, player));
  });

  port = (config != null) && (config.port != null) ? config.port : 8080;

  http.listen(port, function() {
    return console.log('Listening on port %d', port);
  });

}).call(this);
